name: CIForGrpc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
    - name: List directory contents
      run: dir
    - name: Restore dependencies
      run: dotnet restore GrpcCalculatorService/GrpcCalculatorService/GrpcCalculatorService.csproj
    - name: Build
      run: dotnet build GrpcCalculatorService/GrpcCalculatorService/GrpcCalculatorService.csproj --no-restore
    - name: Test
      run: dotnet test GrpcCalculatorService/GrpcCalculatorService/GrpcCalculatorService.csproj --no-build --verbosity normal
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          GrpcCalculatorService/**/bin/Release/net8.0/**
